### ISSUE TITLE
proposed Module rename. -api => -http-client

### ISSUE THREAD

**Issue by daviddias** [hendry19901990/erlang-ipfs-api#2]
Hi! We are considering renaming the IPFS Client libraries, please read more at https://github.com/ipfs/ipfs/issues/374 and comment if you are onboard.

**Comment by hendry19901990** [comment]
This library was renamed erlang-ipfs-client, I'll proceed to close this issue.

**Comment by daviddias** [comment]
@hendry19901990 thank you for being so quick to follow up. After feedback on https://github.com/ipfs/ipfs/issues/374, we reached a conclusion that it would be better to be -ipfs-http-client. Could you rename to it? Sorry for double the work!

**Comment by hendry19901990** [comment]
Don't worry, I already did it. @daviddias

**Comment by daviddias** [comment]
Thank you!
